### PR TITLE
Allow creating log levels that are an empty string or 0. Fixes gh-31

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

### CODE REVIEW

**Comment by zkat** [comment]
Can you give me more context? Is there a specific reason to be able to have this sort of log level?...

**Comment by rwaldron** [comment]
Hi, sorry for the delay in response. For use in t2-cli, we need to be able to print logs like this: 

```
$ t2 list
INFO Searching for nearby Tessels...
	USB	Tessel-02A347EF35F2
```

So I'd like to be able to configure "basic" to have no prefix.

**Comment by rwaldron** [comment]
- Rebased
- Tests updated

**Comment by rwaldron** [comment]
- Rebased

**Comment by rwaldron** [comment]
Any updates on this? Right now we're stuck using my fork in `t2-cli` which means users must have git installed in order to install `t2-cli`. We have [Nodebots Day](https://github.com/nodebots/nodebotsday) coming up and this will be really awful to explain to newcomers (many are literally installing node.js _the day of_) that want to use Tessel 2

**Comment by zkat** [comment]
Looks like the rest of the team signed off on this! We'll be merging it in. Thanks for your time, attention, and for answering all my questions about your use case. :)

**Comment by zkat** [comment]
I've merged this and released `npmlog@4.0.0`. It needed to be a semver-major release because it is incompatible with the previous API, even if we ended up concluding impact would be small. Cheers!

**Pull request closed without merging**
