### PR TITLE
Continue timestamp functionality from Foorack(with a little more)

### PR DESCRIPTION
**Pull request by huan**
This PR include:
1. PR from @Foorack
2. review from @othiym23
3. add enableTimestring() for syslog style time string prefix
4. change lightGrey to grey due to no lightGrey style(in my environment)
5. add enableTimestring & enableTimestamp to example.js
6. add doc & sample output to README

personal, I prefer timestring format like `June 18 10:09:37`, because all the linux syslog use this format. :)

### CODE REVIEW

**Comment by zixia** [comment]
Just fixed the code style so that it can pass unit tests.

**Comment by zixia** [comment]
@othiym23 how about this PR, does there have anything I need to fix, or could we accept it?

**Comment by bsansouci** [comment]
+1 I'd love to have this. npmlog has been working like a charm but having timestamps would really help.

**Comment by Fire7** [comment]
+1

**Comment by Foorack** [comment]
Hello. I still think npmlog is a really good logging library. Having
timestamps would make it even better.

**Comment by zixia** [comment]
@Foorack I love npmlog style so much so that I had created a new `npmlog-liked` module named Brolog.

The Brolog has the following features:
1. API is almost the same as npmlog.
1. Timestamp support.
1. Typescript typing supported.
1. ES6 import supported.(so we have to use `level(silly)` instead of `level = 'silly'`)
1. Run in Browser!
1. Angular Supported(with factory function `Brolog('silly')`)

Brolog NPM: <https://www.npmjs.com/package/brolog>
Brolog GH: <https://github.com/zixia/brolog>

Just want to share what I had done on this feature. Hope this could help others as well.

**Comment by Gcaufy** [comment]
+1
I would be nice if we could have timestamp

**Comment by philraj** [comment]
Doesn't seem like this will ever be merged, so look at this workaround if you want timestamps: https://github.com/npm/npmlog/issues/33#issuecomment-342785666

**Comment by Foorack** [comment]
@huan Brolog doesn't seem to have color output and is therefore not a drop-replacement.

@aeschright This is almost turning 4 years now, if timestamp was implemented then npmlog would be a real contender to the other logging libraries. This package has worked so well for me for so many years but it hurts having to resort to dirty hacks (see previous comment) to get (what should be) basic functionality. Do you know what is preventing this branch from being merged?

**Comment by aeschright** [comment]
I think we just have to nail down the UX and formatting choices. Having both `timestamp` and `timestring` seems pretty confusing to me, can we pick a more descriptive label?

**Pull request closed without merging**
