### PR TITLE
Add progress bar

### PR DESCRIPTION
**Pull request by iarna**
This is the new progress bar code. I'm not entirely happy with how it integrates (see comments on the commits)  but I'm also don't feel that getting it perfect is necessary right now.

### CODE REVIEW

**Comment by iarna** [comment]
Oh, but it already let's you show both the log output and the progress bar at the same time. =)

**Comment by othiym23** [comment]
This piece looks good, modulo the questions I raised. I'll run the tests and take a look at everything with eslint and report back.

Let me know if this is an annoyingly verbose way to do code reviews. We may want to look into setting up a dedicated tool like [Review Board](https://www.reviewboard.org/) if GitHub proves to be too unwieldy, but it would definitely be nice to come up with a more consistent and thorough strategy for reviews, regardless of tooling.

**Comment by othiym23** [comment]
Tests pass on Windows and I've added the few additional things that eslint caught. Fix those and this gets a :thumbsup: from me!

**Comment by iarna** [comment]
I've made the aesthetic changes here (as I said out-of-band, while I may disagree on a fiddly point here and there, I'd rather get this out without any side eye =p) and as there wasn't substantive concerns, I'm going to merge this now.

**Comment by iarna** [comment]
While I'm here I'm gonna bump it to 1.x

**Comment by othiym23** [comment]
:tada:

**Pull request merged**
