### PR TITLE
Add throttling option to enableProgress().

### PR DESCRIPTION
**Pull request by STRML**
Based on slowdowns npmlog is causing as outlined in
https://github.com/npm/npm/issues/11283#issuecomment-175246823

`npm` could then pass a throttling param [on this line](https://github.com/npm/npm/blob/1ac3e088f495bdcba45949ede36e2ad5578f60aa/lib/npm.js#L364).

### CODE REVIEW

**Comment by iarna** [comment]
I think there was some confusion about what and when `enableProgress` is called. It is called in exactly two places:

1. Once, during npm initialization.
2. Once, after disabling the progress bar to run a lifecycle script, only if a lifecycle script is defined.

For most modules, 2 only happens if they have things to compile, so at MOST it will be called once per thing being compiled.

If you fail to reenable the progress bar then it will go away and never come back, because `enableProgress` is only called after a lifecycle script completes if we had to disable it to start, and if you throttled these then it will remain disabled.

If `enableProgress` is being called a lot during an install, that's a bug in `npm`, not in this module, IMO.

**Comment by STRML** [comment]
We're not actually throttling `enableProgress`, we're throttling `showProgress`.

**Comment by STRML** [comment]
@iarna Once this is merged, in combination with the previous patches and a configuration of `100`(ms), I was able to get the `toal` time of `TrackerGroup.completed` down from 61113ms to 64ms.

Before:



After:

**Comment by STRML** [comment]
@iarna Re the v3.7.0 release:

> This [gauge] has been patched to eliminate that churn, and our testing shows the progress bar as being eliminated as a source of slow down.

In the actual profiles:



Note the big red blob is `TrackerGroup.completed`, not anything related to `gauge`.

So the slowdown is still present due to the collection of the data used to display the progress bar, but not the actual display of the progress bar itself.

This PR allows throttling the collection of that data, which is absolutely vital to removing this slowdown.

**Comment by jamesdwilson** [comment]
:+1:

**Comment by iarna** [comment]
Ah, I understand your concern better now, thank you.

I would prefer to make `are-we-there-yet`'s `completed` function not have a cost, rather than just papering over it.

My planned approach is to make the `change` event include the completion numbers. As the bubbled up TrackerGroups would just integrate the new data and emit their overall larger completion numbers. Calls to `.completed()` would get this precomputed number and so for the top level progress bar it would turn a giant recursive tree walk into a single property lookup.

**Comment by STRML** [comment]
That makes sense - will need to be careful to make it very fast, because it is called an obnoxiously large number of times in npm. Best of luck.

**Comment by iarna** [comment]
Yeah, it should actually be possible to avoid calling it all, if we're passing completion data up the chain.

**Comment by iarna** [comment]
I just implemented this over in https://github.com/iarna/are-we-there-yet and if you want to play with it, I have a PR integrating it here: https://github.com/npm/npmlog/pull/28

**Pull request closed without merging**
